# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7z020clg484-1
set_property target_language VHDL [current_project]
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property ip_repo_paths c:/Users/nikolaos.marinos/xil_IP_projects/axi_pulser_receiver_v4 [current_fileset]
read_vhdl {
  C:/Users/nikolaos.marinos/xil_IP_projects/axi_pulser_receiver_v4/axi_pulser_receiver_v4.srcs/sources_1/new/stream_proc.vhd
  C:/Users/nikolaos.marinos/xil_IP_projects/axi_pulser_receiver_v4/axi_pulser_receiver_v4.srcs/sources_1/new/receiver.vhd
  C:/Users/nikolaos.marinos/xil_IP_projects/axi_pulser_receiver_v4/axi_pulser_receiver_v4.srcs/sources_1/new/pulser_1ch_v2.vhd
  C:/Users/nikolaos.marinos/xil_IP_projects/axi_pulser_receiver_v4/axi_pulser_receiver_v4.srcs/sources_1/new/M_AXI_read_data.vhd
  C:/Users/nikolaos.marinos/xil_IP_projects/axi_pulser_receiver_v4/axi_pulser_receiver_v4.srcs/sources_1/new/dataToAxis.vhd
  C:/Users/nikolaos.marinos/xil_IP_projects/axi_pulser_receiver_v4/axi_pulser_receiver_v4.srcs/sources_1/new/control_unit.vhd
  C:/Users/nikolaos.marinos/xil_IP_projects/axi_pulser_receiver_v4/axi_pulser_receiver_v4.srcs/sources_1/new/axi_pulser_receiver_v4.vhd
}
read_xdc C:/Users/nikolaos.marinos/xil_IP_projects/axi_pulser_receiver_v4/axi_pulser_receiver_v4.srcs/constrs_1/new/axi_pulser_receiver_v4.xdc
set_property used_in_implementation false [get_files C:/Users/nikolaos.marinos/xil_IP_projects/axi_pulser_receiver_v4/axi_pulser_receiver_v4.srcs/constrs_1/new/axi_pulser_receiver_v4.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/nikolaos.marinos/xil_IP_projects/axi_pulser_receiver_v4/axi_pulser_receiver_v4.data/wt [current_project]
set_property parent.project_dir C:/Users/nikolaos.marinos/xil_IP_projects/axi_pulser_receiver_v4 [current_project]
synth_design -top axi_pulser_receiver_v4 -part xc7z020clg484-1
write_checkpoint axi_pulser_receiver_v4.dcp
report_utilization -file axi_pulser_receiver_v4_utilization_synth.rpt -pb axi_pulser_receiver_v4_utilization_synth.pb
